samples:
 - Br1A # Juvenile
 - Br4A
 - E4A
 - E5A
 - G3A
 - G4A
 - GN2A
 - GN3A
 - H2A
 - H3A
 - K1A
 - K2A
 - L1A
 - L3A
 - ln2A
 - ln3A
 - M3A
 - M4A
 - GTS-Br-11-2A # Adult  (10, 11, and 12 is male; 13, 14, and 15 is female)
 - GTS-Br-12-1A
 - GTS-Br-13-1A
 - GTS-Br-14-1A
 - GTS-E-10-2A
 - GTS-E-12-2A
 - GTS-E-14-2A
 - GTS-E-15-2A
 - GTS-G-10-2A
 - GTS-G-11-2A
 - GTS-G-14-2A
 - GTS-G-15-2A
 - GTS-GN-10-2A
 - GTS-GN-11-2A
 - GTS-GN-13-2A
 - GTS-GN-14-2A
 - GTS-He-11-2A
 - GTS-He-12-2A
 - GTS-He-13-2A
 - GTS-He-14-2A
 - GTS-K-11-2A
 - GTS-K-12-2A
 - GTS-K-13-2A
 - GTS-K-14-2A
 - GTS-L-10-2A
 - GTS-L-11-2A
 - GTS-L-13-2A
 - GTS-L-14-2A
 - GTS-M-10-2A
 - GTS-M-11-2A
 - GTS-M-13-2A
 - GTS-M-14-2A
 - GTS-MT-10-2A
 - GTS-MT-11-2A
 - GTS-MT-13-2A
 - GTS-MT-14-2A
 - GTS-P-10A
 - GTS-P-11A
 - GTS-P-13A
 - GTS-P-14A
 - GTS-S-11-2A
 - GTS-S-12-2A
 - GTS-S-13-2A
 - GTS-S-14-2A
 - GTS-St-10-2A
 - GTS-St-11-2A
 - GTS-St-13-2A
 - GTS-St-14-2A

threads: 20
