builds:
 - ncbi
 - ensembl
 - ngs
 - tgs
genome: ../common/ncbi/serDum.genome.fa
ncbi: ../common/ncbi/serDum.annotation.filtered.no_mito.sorted.gtf.gz
ensembl: ../common/ensembl/serDum.annotation.converted.filtered.no_mito.sorted.gtf.gz
ngs: ../1_RNA-seq/results/assembly/taco/stringtie.gtf.gz
tgs: ../2_Iso-seq/results/assembly/cupcake/collapsed/all.filtered.gtf.gz